// ============================================================
// DYNASTY BRUHHH DUNGEON - Localization (Việt Hóa)
// Must load BEFORE all other scripts
// ============================================================

const LANG = {
    _current: 'vi', // Default Vietnamese

    // ===== VIETNAMESE =====
    vi: {
        // --- Game Title ---
        title: 'VƯƠNG TRIỀU BRUHHH — HẦM NGỤC',
        subtitle: 'Phiên Bản Cao Cấp',
        pressStart: 'Nhấn để bắt đầu',

        // --- Menu ---
        menuStart: 'BẮT ĐẦU',
        menuContinue: 'TIẾP TỤC',
        menuSettings: 'CÀI ĐẶT',
        menuLanguage: 'NGÔN NGỮ',
        selectHero: 'CHỌN TƯỚNG',
        startBattle: 'XUẤT TRẬN',

        // --- Heroes ---
        hero_berserker: 'Lữ Bố',
        hero_berserker_title: 'Chiến Thần',
        hero_strategist: 'Gia Cát Lượng',
        hero_strategist_title: 'Ngọa Long',
        hero_assassin: 'Chu Du',
        hero_assassin_title: 'Tiểu Bá Vương',
        hero_vanguard: 'Triệu Vân',
        hero_vanguard_title: 'Thường Sơn Long',
        hero_mystic: 'Tư Mã Ý',
        hero_mystic_title: 'Ẩn Long',
        hero_ranger: 'Hoàng Trung',
        hero_ranger_title: 'Lão Tướng Thần Xạ',

        // --- Hero Passives ---
        passive_comboRage: 'Cuồng Nộ Chiến',
        passive_comboRage_desc: '+2% ST mỗi combo (tối đa 50%)',
        passive_xpBonus: 'Trí Tuệ Tuyệt Đỉnh',
        passive_xpBonus_desc: '+30% KN, 4 lựa chọn khi lên cấp',
        passive_critChance: 'Lưỡi Kiếm Tử Thần',
        passive_critChance_desc: '20% bạo kích, bạo kích x3 sát thương',
        passive_tankAura: 'Bất Khuất',
        passive_tankAura_desc: '-20% ST nhận, +10% HP đồng đội',
        passive_necro: 'Tà Thuật Hắc Ám',
        passive_necro_desc: '10% kẻ bị giết hồi sinh thành lính 8s',
        passive_eagleEye: 'Mắt Ưng',
        passive_eagleEye_desc: 'Tầm xa +30%, ST tăng theo khoảng cách',

        // --- Tactical Skills ---
        tac_ground_slam: 'Chấn Địa',
        tac_ground_slam_desc: 'AoE choáng xung quanh',
        tac_wind_burst: 'Cuồng Phong',
        tac_wind_burst_desc: 'Hình nón đẩy lùi + làm chậm',
        tac_shadow_strike: 'Ám Kích',
        tac_shadow_strike_desc: 'Dịch chuyển + đâm sau lưng',
        tac_shield_wall: 'Thiết Bích',
        tac_shield_wall_desc: 'Chặn mọi sát thương 2.5s',
        tac_life_drain: 'Hút Sinh Lực',
        tac_life_drain_desc: 'Hút 30 HP từ kẻ địch gần',
        tac_arrow_rain: 'Mưa Tên',
        tac_arrow_rain_desc: 'Bão phi tiêu rơi xuống AoE',

        // --- Ultimate Skills ---
        ult_rage_mode: 'Cuồng Nộ Thiên Hạ',
        ult_rage_mode_desc: 'x2 ST + x1.5 tốc độ trong 6s',
        ult_eight_trigrams: 'Bát Quái Trận',
        ult_eight_trigrams_desc: '8 đạn nguyên tố xoáy tròn',
        ult_blade_storm: 'Bão Kiếm',
        ult_blade_storm_desc: 'Lao qua mọi kẻ địch gần',
        ult_changban_charge: 'Trường Bản Trận',
        ult_changban_charge_desc: 'Bất khả xâm phạm + nổ AoE',
        ult_phoenix_summon: 'Phụng Hoàng Thánh',
        ult_phoenix_summon_desc: 'Triệu hồi Phụng — lửa AoE + hồi',
        ult_shuriken_storm: 'Vạn Tiễn Tề Phát',
        ult_shuriken_storm_desc: 'Bão phi tiêu xoáy bốn phương',

        // --- Weapons ---
        wpn_fire_halberd: 'Thiên Phương Họa Kích',
        wpn_wood_fan: 'Vũ Phiến Luân Cân',
        wpn_metal_twin: 'Song Kiếm',
        wpn_earth_spear: 'Long Đảm Thương',
        wpn_water_scepter: 'Ám Kỳ Trượng',
        wpn_wood_shuriken: 'Phi Tiêu Mộc',
        wpn_fire_sword: 'Hỏa Kiếm',
        wpn_metal_blade: 'Bão Nhẫn Kim',
        wpn_water_bolt: 'Băng Tiễn Liên Hoàn',
        wpn_wood_vine: 'Cổ Thụ Trận',
        wpn_earth_wall: 'Địa Thuẫn',
        wpn_fire_pillar: 'Hỏa Trụ',
        wpn_metal_rain: 'Mưa Kim Loại',
        wpn_water_wave: 'Thủy Triều',
        wpn_wood_heal: 'Sinh Mệnh Thuật',
        wpn_earth_quake: 'Địa Chấn',
        wpn_fire_kunai: 'Hỏa Phi Đao',
        wpn_metal_crossbow: 'Kim Nỏ Liên Châu',

        // --- Weapon Descriptions ---
        wpn_fire_sword_desc: 'Chém lửa phía trước',
        wpn_metal_blade_desc: 'Nhẫn xoay quanh người',
        wpn_water_bolt_desc: 'Băng tiễn nảy tự động giữa kẻ thù',
        wpn_wood_vine_desc: 'Cây cối hồi HP + sát thương gần',
        wpn_earth_wall_desc: 'Hào quang phòng thủ + sát thương',
        wpn_fire_pillar_desc: 'Cột lửa phun trào',
        wpn_metal_rain_desc: 'Mưa mảnh kim loại',
        wpn_water_wave_desc: 'Quét sóng rộng',
        wpn_wood_heal_desc: 'Hồi 20% HP',
        wpn_earth_quake_desc: 'Đập đất, choáng gần',
        wpn_fire_kunai_desc: 'Phi đao lửa, xuyên + cháy',
        wpn_metal_crossbow_desc: 'Nỏ liên châu tốc độ cao',
        wpn_wood_shuriken_desc: 'Phi tiêu quạt 3 hướng, tầm xa',

        // --- Passives ---
        wpn_atk_speed: 'Tốc Chiến',
        wpn_atk_speed_desc: '+20% tốc độ đánh',
        wpn_max_hp: 'Sinh Lực',
        wpn_max_hp_desc: '+25 HP tối đa',
        wpn_move_spd: 'Phi Bộ',
        wpn_move_spd_desc: '+15% tốc độ di chuyển',
        wpn_pickup_range: 'Hấp Dẫn',
        wpn_pickup_range_desc: '+50% tầm nhặt',
        wpn_xp_gain: 'Học Giả',
        wpn_xp_gain_desc: '+25% kinh nghiệm',

        // --- Elements ---
        el_WOOD: 'Mộc',
        el_FIRE: 'Hỏa',
        el_EARTH: 'Thổ',
        el_METAL: 'Kim',
        el_WATER: 'Thủy',
        el_symbol_WOOD: '木',
        el_symbol_FIRE: '火',
        el_symbol_EARTH: '土',
        el_symbol_METAL: '金',
        el_symbol_WATER: '水',

        // --- Morale ---
        morale_label: 'SĨ KHÍ',
        morale_wavering: 'Dao Động',
        morale_steady: 'Ổn Định',
        morale_high: 'Hào Khí',
        morale_overwhelming: 'ÁP ĐẢO!',

        // --- HUD ---
        hud_floor: 'Tầng',
        hud_level: 'Cấp',
        hud_combo: 'Liên',
        hud_kills: 'Hạ',
        hud_gold: 'Vàng',
        hud_hp: 'HP',
        hud_mp: 'MP',
        hud_musou: 'Vô Song',
        hud_fps: 'FPS',
        hud_wave: 'Đợt',
        hud_clear: 'Dọn sạch',
        hud_portal: 'Cổng dịch chuyển đã mở!',
        hud_dodge: 'Né',
        hud_tactical: 'Chiến Thuật',
        hud_ultimate: 'Tuyệt Chiêu',
        hud_warCry: 'CHIẾN HÁO!',
        hud_equipment: 'Trang Bị',
        hud_allies: 'Đồng Đội',
        hud_version: 'P.B.',

        // --- Announcements ---
        ann_bossIncoming: '⚠ BOSS SẮP ĐẾN ⚠',
        ann_generalDefeated: 'ĐÃ HẠ!',
        ann_newFloor: 'TẦNG MỚI',
        ann_weaponEvolved: '⚡ VŨ KHÍ TIẾN HÓA! ⚡',
        ann_levelUp: 'TĂNG CẤP!',
        ann_killMilestone: 'CHÁY!',
        ann_treasureRoom: 'PHÒNG KHO BÁU',
        ann_comboBreak: 'MẤT COMBO',
        ann_brotherhood: 'KẾT NGHĨA KÍCH HOẠT!',

        // --- Level Up ---
        lvlup_title: 'CHỌN NÂNG CẤP',
        lvlup_new: 'MỚI',
        lvlup_upgrade: 'LÊN CẤP',
        lvlup_evolved: 'TIẾN HÓA',

        // --- Game Over ---
        gameover_title: 'TỬ TRẬN',
        gameover_score: 'Điểm',
        gameover_floor: 'Tầng',
        gameover_kills: 'Hạ gục',
        gameover_maxCombo: 'Combo cao nhất',
        gameover_retry: 'Thử lại',

        // --- Equipment ---
        eq_armor: 'Giáp',
        eq_talisman: 'Bùa',
        eq_mount: 'Ngựa',
        eq_common: 'Thường',
        eq_uncommon: 'Hiếm',
        eq_rare: 'Quý Hiếm',
        eq_legendary: 'Huyền Thoại',
        eq_sacred: 'Thần Thánh',

        // --- Mounts ---
        mount_war_horse: 'Chiến Mã',
        mount_shadow_steed: 'Ám Ảnh Mã',
        mount_hex_mark: 'Lục Dấu',
        mount_red_hare: 'Xích Thố',
        mount_jade_qilin: 'Ngọc Kỳ Lân',

        // --- Bonds ---
        bond_peach_oath: 'Đào Viên Kết Nghĩa',
        bond_peach_oath_desc: 'Huynh đệ kết nghĩa bảo vệ',
        bond_five_tigers: 'Ngũ Hổ Tướng',
        bond_five_tigers_desc: '+ST mỗi vũ khí trang bị',
        bond_dragon_phoenix: 'Long Phụng',
        bond_dragon_phoenix_desc: 'Tăng nguyên tố combo',
        bond_cao_elites: 'Ngũ Tử Lương Tướng',
        bond_cao_elites_desc: 'Hào quang phòng thủ',
        bond_wei_ambition: 'Hùng Tâm Ngụy Quốc',
        bond_wei_ambition_desc: '+KN và vàng',
        bond_sun_legacy: 'Tôn Gia Di Sản',
        bond_sun_legacy_desc: 'Tăng tốc độ đánh',
        bond_red_cliffs: 'Đồng Minh Xích Bích',
        bond_red_cliffs_desc: 'Sát thương lửa & cháy',
        bond_tragic_romance: 'Bi Tình Lữ Bố',
        bond_tragic_romance_desc: 'Max ST, max rủi ro',
        bond_brilliant_rivals: 'Kỳ Phùng Địch Thủ',
        bond_brilliant_rivals_desc: 'Tăng tốc tiến hóa vũ khí',

        // --- Brotherhood Combos ---
        combo_peach_rush: 'Đào Viên Hợp Kích',
        combo_peach_rush_desc: 'Ba anh em xung phong!',
        combo_tiger_roar: 'Hổ Khí Xung Thiên',
        combo_tiger_roar_desc: 'Ngũ Hổ Tướng gầm vang!',
        combo_dragon_phoenix_storm: 'Long Phụng Trình Tường',
        combo_dragon_phoenix_storm_desc: 'Bão nguyên tố chéo!',
        combo_red_cliffs_inferno: 'Xích Bích Đại Hỏa',
        combo_red_cliffs_inferno_desc: 'Lửa trời thiêu cháy!',

        // --- Generals (Mini-bosses) ---
        gen_dong_zhuo: 'Đổng Trác',
        gen_dong_zhuo_title: 'Bạo Chúa',
        gen_yuan_shao: 'Viên Thiệu',
        gen_yuan_shao_title: 'Quý Tộc',
        gen_cao_cao: 'Tào Tháo',
        gen_cao_cao_title: 'Gian Hùng',
        gen_sun_jian: 'Tôn Kiên',
        gen_sun_jian_title: 'Mãnh Hổ Giang Đông',
        gen_diao_chan: 'Điêu Thuyền',
        gen_diao_chan_title: 'Mỹ Nhân Kế',
        gen_guan_yu: 'Quan Vũ',
        gen_guan_yu_title: 'Võ Thánh',
        gen_zhang_fei: 'Trương Phi',
        gen_zhang_fei_title: 'Vạn Nhân Địch',
        gen_lu_bu: 'Lữ Bố',
        gen_lu_bu_title: 'Chiến Thần',
        gen_sun_ce: 'Tôn Sách',
        gen_sun_ce_title: 'Tiểu Bá Vương',
        gen_zhang_liao: 'Trương Liêu',
        gen_zhang_liao_title: 'Oai Trấn Tiêu Dao',

        // --- Ally Aura ---
        aura_tank: 'THIẾT BÍCH',
        aura_melee: 'CUỒNG CHIẾN',
        aura_ranged: 'TINH CHUẨN',

        // --- Companion names ---
        comp_liu_bei: 'Lưu Bị',
        comp_guan_yu: 'Quan Vũ',
        comp_zhang_fei: 'Trương Phi',
        comp_zhuge_liang: 'Gia Cát Lượng',
        comp_pang_tong: 'Bàng Thống',
        comp_ma_chao: 'Mã Siêu',
        comp_cao_cao: 'Tào Tháo',
        comp_sima_yi: 'Tư Mã Ý',
        comp_guo_jia: 'Quách Gia',
        comp_xu_chu: 'Hứa Chử',
        comp_zhang_liao: 'Trương Liêu',
        comp_zhou_yu: 'Chu Du',
        comp_huang_gai: 'Hoàng Cái',
        comp_sun_ce: 'Tôn Sách',
        comp_zhou_tai: 'Chu Thái',

        // --- Misc ---
        misc_crit: 'BẠO KÍCH!',
        misc_superEffective: 'KHẮC CHẾ!',
        misc_revive: 'HỒI SINH!',
        misc_yinYang: 'Âm Dương',
        misc_yin: 'Âm',
        misc_yang: 'Dương',
        misc_balance: 'Quân Bình',
        misc_yinDom: 'Âm Thịnh',
        misc_yangDom: 'Dương Thịnh',
        misc_darkness: 'Hắc Ám',
        misc_grasp: 'Ý Chí',
        misc_bonds: 'Kết Nghĩa',
        misc_skills: 'Kỹ Năng',
        misc_equip: 'Trang Bị',
        misc_back: 'Quay Lại',
        misc_confirm: 'Xác Nhận',
        misc_brotherhood: 'HUYNH ĐỆ',
        misc_comboGauge: 'Hợp Kích',
        misc_activate: 'Kích Hoạt [R]',
    },

    // ===== ENGLISH =====
    en: {
        title: 'DYNASTY BRUHHH DUNGEON',
        subtitle: 'Premium Edition',
        pressStart: 'Press to Start',
        menuStart: 'START',
        menuContinue: 'CONTINUE',
        menuSettings: 'SETTINGS',
        menuLanguage: 'LANGUAGE',
        selectHero: 'SELECT HERO',
        startBattle: 'START BATTLE',
        hero_berserker: 'Lu Bu',
        hero_berserker_title: 'God of War',
        hero_strategist: 'Zhuge Liang',
        hero_strategist_title: 'Sleeping Dragon',
        hero_assassin: 'Zhou Yu',
        hero_assassin_title: 'Young Conqueror',
        hero_vanguard: 'Zhao Yun',
        hero_vanguard_title: 'Dragon of Changshan',
        hero_mystic: 'Sima Yi',
        hero_mystic_title: 'Hidden Dragon',
        hero_ranger: 'Huang Zhong',
        hero_ranger_title: 'The Veteran Archer',
        passive_comboRage: 'Blood Rage',
        passive_comboRage_desc: '+2% DMG per combo (max 50%)',
        passive_xpBonus: 'Brilliant Mind',
        passive_xpBonus_desc: '+30% XP, 4 level-up choices',
        passive_critChance: 'Lethal Edge',
        passive_critChance_desc: '20% crit chance, crits deal 3x',
        passive_tankAura: 'Unbreakable',
        passive_tankAura_desc: '-20% damage taken, +10% ally HP',
        passive_necro: 'Dark Wisdom',
        passive_necro_desc: '10% killed enemies rise as allies 8s',
        passive_eagleEye: 'Eagle Eye',
        passive_eagleEye_desc: 'Range +30%, DMG scales with distance',
        tac_ground_slam: 'Ground Slam',
        tac_ground_slam_desc: 'AoE stun around player',
        tac_wind_burst: 'Wind Burst',
        tac_wind_burst_desc: 'Cone knockback + slow',
        tac_shadow_strike: 'Shadow Strike',
        tac_shadow_strike_desc: 'Teleport to nearest + backstab',
        tac_shield_wall: 'Shield Wall',
        tac_shield_wall_desc: 'Block all damage for 2.5s',
        tac_life_drain: 'Life Drain',
        tac_life_drain_desc: 'Steal 30 HP from nearby enemies',
        tac_arrow_rain: 'Arrow Rain',
        tac_arrow_rain_desc: 'Shuriken barrage rains down AoE',
        ult_rage_mode: 'Dynasty Fury',
        ult_rage_mode_desc: '2x damage + 1.5x speed for 6s',
        ult_eight_trigrams: 'Eight Trigrams',
        ult_eight_trigrams_desc: '8 elemental bolts spiral out',
        ult_blade_storm: 'Blade Storm',
        ult_blade_storm_desc: 'Dash through all nearby enemies',
        ult_changban_charge: 'Changban Charge',
        ult_changban_charge_desc: 'Invincible charge + AoE explosion',
        ult_phoenix_summon: 'Sacred Phoenix',
        ult_phoenix_summon_desc: 'Summon Phoenix — fire AoE + heal',
        ult_shuriken_storm: 'Shuriken Storm',
        ult_shuriken_storm_desc: 'Whirlwind of homing shuriken',
        wpn_fire_halberd: 'Sky Piercer',
        wpn_wood_fan: 'Feather Fan',
        wpn_metal_twin: 'Twin Blades',
        wpn_earth_spear: 'Dragon Spear',
        wpn_water_scepter: 'Dark Scepter',
        wpn_wood_shuriken: 'Wind Shuriken',
        wpn_fire_sword: 'Fire Sword',
        wpn_metal_blade: 'Blade Storm',
        wpn_water_bolt: 'Chain Frost Bolt',
        wpn_wood_vine: 'Root Zone',
        wpn_earth_wall: 'Earth Shield',
        wpn_fire_pillar: 'Fire Pillar',
        wpn_metal_rain: 'Arrow Rain',
        wpn_water_wave: 'Tidal Wave',
        wpn_wood_heal: 'Life Surge',
        wpn_earth_quake: 'Earthquake',
        wpn_fire_kunai: 'Flame Kunai',
        wpn_metal_crossbow: 'Repeating Crossbow',
        wpn_fire_sword_desc: 'Forward fire slash',
        wpn_metal_blade_desc: 'Spinning blades orbit you',
        wpn_water_bolt_desc: 'Auto-chains between enemies',
        wpn_wood_vine_desc: 'Healing vines damage nearby foes',
        wpn_earth_wall_desc: 'Damage aura + defense up',
        wpn_fire_pillar_desc: 'Erupting flame pillars',
        wpn_metal_rain_desc: 'Raining metal shards',
        wpn_water_wave_desc: 'Wide water sweep',
        wpn_wood_heal_desc: 'Heal 20% HP over time',
        wpn_earth_quake_desc: 'Ground slam, stuns nearby',
        wpn_fire_kunai_desc: 'Piercing flame kunai + burnDOT',
        wpn_metal_crossbow_desc: 'Rapid-fire crossbow bolts',
        wpn_wood_shuriken_desc: '3-fan spread shuriken, long range',
        wpn_atk_speed: 'Swift Strikes',
        wpn_atk_speed_desc: '+20% attack speed',
        wpn_max_hp: 'Vitality',
        wpn_max_hp_desc: '+25 max HP',
        wpn_move_spd: 'Fleet Foot',
        wpn_move_spd_desc: '+15% move speed',
        wpn_pickup_range: 'Magnet',
        wpn_pickup_range_desc: '+50% pickup range',
        wpn_xp_gain: 'Scholar',
        wpn_xp_gain_desc: '+25% XP gain',
        el_WOOD: 'Wood', el_FIRE: 'Fire', el_EARTH: 'Earth', el_METAL: 'Metal', el_WATER: 'Water',
        el_symbol_WOOD: '木', el_symbol_FIRE: '火', el_symbol_EARTH: '土', el_symbol_METAL: '金', el_symbol_WATER: '水',
        morale_label: 'MORALE',
        morale_wavering: 'Wavering',
        morale_steady: 'Steady',
        morale_high: 'High Spirits',
        morale_overwhelming: 'OVERWHELMING!',
        hud_floor: 'Floor',
        hud_level: 'Lv',
        hud_combo: 'Combo',
        hud_kills: 'Kills',
        hud_gold: 'Gold',
        hud_hp: 'HP',
        hud_mp: 'MP',
        hud_musou: 'Musou',
        hud_fps: 'FPS',
        hud_wave: 'Wave',
        hud_clear: 'Clear',
        hud_portal: 'Portal has opened!',
        hud_dodge: 'Dodge',
        hud_tactical: 'Tactical',
        hud_ultimate: 'Ultimate',
        hud_warCry: 'WAR CRY!',
        hud_equipment: 'Equipment',
        hud_allies: 'Allies',
        hud_version: 'v',
        ann_bossIncoming: '⚠ BOSS INCOMING ⚠',
        ann_generalDefeated: 'DEFEATED!',
        ann_newFloor: 'NEW FLOOR',
        ann_weaponEvolved: '⚡ WEAPON EVOLVED! ⚡',
        ann_levelUp: 'LEVEL UP!',
        ann_killMilestone: 'ON FIRE!',
        ann_treasureRoom: 'TREASURE ROOM',
        ann_comboBreak: 'COMBO BREAK',
        ann_brotherhood: 'BROTHERHOOD ACTIVATED!',
        lvlup_title: 'CHOOSE UPGRADE',
        lvlup_new: 'NEW',
        lvlup_upgrade: 'UPGRADE',
        lvlup_evolved: 'EVOLVED',
        gameover_title: 'FALLEN IN BATTLE',
        gameover_score: 'Score',
        gameover_floor: 'Floor',
        gameover_kills: 'Kills',
        gameover_maxCombo: 'Max Combo',
        gameover_retry: 'Retry',
        eq_armor: 'Armor', eq_talisman: 'Talisman', eq_mount: 'Mount',
        eq_common: 'Common', eq_uncommon: 'Uncommon', eq_rare: 'Rare',
        eq_legendary: 'Legendary', eq_sacred: 'Sacred',
        mount_war_horse: 'War Horse', mount_shadow_steed: 'Shadow Steed',
        mount_hex_mark: 'Hex Mark', mount_red_hare: 'Red Hare',
        mount_jade_qilin: 'Jade Qilin',
        bond_peach_oath: 'Peach Garden Oath',
        bond_peach_oath_desc: 'Sworn brothers protect',
        bond_five_tigers: 'Five Tiger Generals',
        bond_five_tigers_desc: '+DMG per weapon equipped',
        bond_dragon_phoenix: 'Dragon & Phoenix',
        bond_dragon_phoenix_desc: 'Elemental mastery boost',
        bond_cao_elites: "Cao's Five Elites",
        bond_cao_elites_desc: 'Defense wall aura',
        bond_wei_ambition: 'Ambition of Wei',
        bond_wei_ambition_desc: '+XP and gold gain',
        bond_sun_legacy: 'Sun Family Legacy',
        bond_sun_legacy_desc: 'Attack speed boost',
        bond_red_cliffs: 'Red Cliffs Alliance',
        bond_red_cliffs_desc: 'Fire damage & burn',
        bond_tragic_romance: 'Tragic Romance',
        bond_tragic_romance_desc: 'Max power, max risk',
        bond_brilliant_rivals: 'Brilliant Rivals',
        bond_brilliant_rivals_desc: 'Weapon evolution speed',
        combo_peach_rush: 'Peach Garden Rush',
        combo_peach_rush_desc: 'Three brothers charge!',
        combo_tiger_roar: 'Tiger Generals Roar',
        combo_tiger_roar_desc: 'Five Tigers roar!',
        combo_dragon_phoenix_storm: 'Dragon Phoenix Storm',
        combo_dragon_phoenix_storm_desc: 'Elemental cross storm!',
        combo_red_cliffs_inferno: 'Red Cliffs Inferno',
        combo_red_cliffs_inferno_desc: 'Heavenly fire burns all!',
        gen_dong_zhuo: 'Dong Zhuo', gen_dong_zhuo_title: 'The Tyrant',
        gen_yuan_shao: 'Yuan Shao', gen_yuan_shao_title: 'The Noble',
        gen_cao_cao: 'Cao Cao', gen_cao_cao_title: 'The Strategist',
        gen_sun_jian: 'Sun Jian', gen_sun_jian_title: 'The Tiger',
        gen_diao_chan: 'Diao Chan', gen_diao_chan_title: 'The Enchantress',
        gen_guan_yu: 'Guan Yu', gen_guan_yu_title: 'God of War',
        gen_zhang_fei: 'Zhang Fei', gen_zhang_fei_title: 'The Unmatched',
        gen_lu_bu: 'Lu Bu', gen_lu_bu_title: 'God of War',
        gen_sun_ce: 'Sun Ce', gen_sun_ce_title: 'Little Conqueror',
        gen_zhang_liao: 'Zhang Liao', gen_zhang_liao_title: 'Terror of Xiaoyao',
        aura_tank: 'SHIELD', aura_melee: 'FURY', aura_ranged: 'PRECISION',
        comp_liu_bei: 'Liu Bei', comp_guan_yu: 'Guan Yu', comp_zhang_fei: 'Zhang Fei',
        comp_zhuge_liang: 'Zhuge Liang', comp_pang_tong: 'Pang Tong', comp_ma_chao: 'Ma Chao',
        comp_cao_cao: 'Cao Cao', comp_sima_yi: 'Sima Yi', comp_guo_jia: 'Guo Jia',
        comp_xu_chu: 'Xu Chu', comp_zhang_liao: 'Zhang Liao', comp_zhou_yu: 'Zhou Yu',
        comp_huang_gai: 'Huang Gai', comp_sun_ce: 'Sun Ce', comp_zhou_tai: 'Zhou Tai',
        misc_crit: 'CRITICAL!', misc_superEffective: 'SUPER EFFECTIVE!',
        misc_revive: 'REVIVED!', misc_yinYang: 'Yin-Yang',
        misc_yin: 'Yin', misc_yang: 'Yang', misc_balance: 'Balance',
        misc_yinDom: 'Yin Dominance', misc_yangDom: 'Yang Dominance',
        misc_darkness: 'Darkness', misc_grasp: 'Grasp',
        misc_bonds: 'Bonds', misc_skills: 'Skills', misc_equip: 'Equipment',
        misc_back: 'Back', misc_confirm: 'Confirm',
        misc_brotherhood: 'BROTHERHOOD', misc_comboGauge: 'Combo',
        misc_activate: 'Activate [R]',
    }
};

// --- Translation Helper ---
function t(key) {
    const lang = LANG[LANG._current] || LANG.vi;
    return lang[key] || LANG.en[key] || key;
}

// --- Switch Language ---
function setLang(langCode) {
    if (LANG[langCode]) {
        LANG._current = langCode;
    }
}

// --- Get companion localized name ---
function tComp(engName) {
    const key = 'comp_' + engName.toLowerCase().replace(/ /g, '_');
    return t(key) || engName;
}

// --- Get general localized name ---
function tGen(engName) {
    const key = 'gen_' + engName.toLowerCase().replace(/ /g, '_');
    return t(key) || engName;
}

// --- Get general localized title ---
function tGenTitle(engName) {
    const key = 'gen_' + engName.toLowerCase().replace(/ /g, '_') + '_title';
    return t(key) || '';
}
