// ============================================================
// DYNASTY BRUHHH DUNGEON - Procedural Pixel Art Sprites
// ============================================================
// All sprites defined as 2D color arrays. '.' = transparent.
// Draw function renders each pixel as a fillRect.

const SPRITE_SCALE = 1; // Each sprite pixel = 1 game pixel

// --- Color Palette ---
const PAL = {
    // Skin tones
    skin: '#e8c170', skinShadow: '#b8894a', skinLight: '#ffe0a0',
    // Hair/Dark
    hair: '#4a3728', hairDark: '#2a1f16',
    // Eyes
    eyeW: '#ffffff', eyeP: '#222222',
    // Armor base
    armorShu: '#cc3333', armorWei: '#3366bb', armorWu: '#33aa33',
    // Metal
    metal: '#8899aa', metalLight: '#bbccdd', metalDark: '#556677',
    // Leather
    leather: '#6b4423', leatherDark: '#4a2f15',
    // Enemy colors  
    skeleton: '#ccccbb', skeletonDark: '#999988',
    demon: '#aa2222', demonDark: '#771111', demonGlow: '#ff4444',
    shadow: '#443366', shadowDark: '#221144',
    beast: '#886633', beastDark: '#664422',
    // Effects
    gold: '#ffdd00', goldLight: '#ffee66',
    blood: '#881111',
};

// Helper: parse sprite string into 2D array
function parseSpriteStr(str, colorMap) {
    return str.trim().split('\n').map(row =>
        row.trim().split('').map(ch => colorMap[ch] || null)
    );
}

// --- PLAYER SPRITES ---
const PLAYER_COLORS = {
    '.': null, ' ': null,
    'H': PAL.hair, 'h': PAL.hairDark,
    'S': PAL.skin, 's': PAL.skinShadow, 'L': PAL.skinLight,
    'E': PAL.eyeW, 'P': PAL.eyeP,
    'A': null, 'a': null, // Armor - set dynamically per element
    'M': PAL.metal, 'm': PAL.metalDark,
    'B': PAL.leather, 'b': PAL.leatherDark,
};

const PLAYER_FRAMES = {
    idle: [
        // Frame 0 - Standing (12w x 16h)
        `....HHHH....
...HHhHHH..
...HSSHH...
...SEEBS...
...SPPSB...
....SSSS...
..AAAAAA..
..AAmMAA..
..A.AA.A..
..AAAAAA..
...BBBB...
...B..B...
...B..B...
...b..b...
...MM.MM..
...MM.MM..`,
        // Frame 1 - Idle breathe
        `....HHHH....
...HHhHHH..
...HSSHH...
...SEEBS...
...SPPSB...
....SSSS...
..AAAAAA..
..AAmMAA..
..A.AA.A..
..AAAAAA..
...BBBB...
...B..B...
...B..B...
...b..b...
..MM..MM..
..MM..MM..`,
    ],
    walk: [
        // Frame 0 - Left leg forward
        `....HHHH....
...HHhHHH..
...HSSHH...
...SEEBS...
...SPPSB...
....SSSS...
..AAAAAA..
..AAmMAA..
..A.AA.A..
..AAAAAA..
...BBBB...
...B..B...
..B....B..
..b....b..
..MM..MM..
.MM....MM.`,
        // Frame 1 - Right leg forward
        `....HHHH....
...HHhHHH..
...HSSHH...
...SEEBS...
...SPPSB...
....SSSS...
..AAAAAA..
..AAmMAA..
..A.AA.A..
..AAAAAA..
...BBBB...
...B..B...
....BB....
....bb....
...MMMM...
...MMMM...`,
        // Frame 2 - Neutral
        `....HHHH....
...HHhHHH..
...HSSHH...
...SEEBS...
...SPPSB...
....SSSS...
..AAAAAA..
..AAmMAA..
..A.AA.A..
..AAAAAA..
...BBBB...
...B..B...
...B..B...
...b..b...
...MM.MM..
...MM.MM..`,
        // Frame 3 - Right leg forward (mirror of 0)
        `....HHHH....
...HHhHHH..
...HSSHH...
...SEEBS...
...SPPSB...
....SSSS...
..AAAAAA..
..AAmMAA..
..A.AA.A..
..AAAAAA..
...BBBB...
...B..B...
....BB....
....bb....
..MM..MM..
.MM....MM.`,
    ],
    attack: [
        // Frame 0 - Wind up
        `....HHHH....
...HHhHHH..
...HSSHH...
...SEEBS...
...SPPSB...
....SSSS...
.AAAAAAAM.
.AAmMAAMM.
.A.AA.AMM.
..AAAAAA..
...BBBB...
...B..B...
..B....B..
..b....b..
..MM..MM..
..MM..MM..`,
        // Frame 1 - Swinging
        `....HHHH....
...HHhHHH..
...HSSHH...
...SEEBS...
...SPPSB...
....SSSS...
..AAAAAAMMM
..AAmMAAAAM
..A.AA.A..M
..AAAAAA...
...BBBB....
...B..B....
...B..B....
...b..b....
...MM.MM...
...MM.MM...`,
    ],
};

// --- ENEMY SPRITES ---
const ENEMY_SPRITES = {
    grunt: {
        colors: {
            '.': null, ' ': null,
            'B': '#667788', 'b': '#445566', // Body
            'E': '#ff3333', 'e': '#cc0000', // Eyes
            'S': PAL.skeleton, 's': PAL.skeletonDark,
            'M': PAL.metal, 'm': PAL.metalDark,
            'H': '#556677',
        },
        frames: [
            // 10x12 grunt warrior
            `...MMMM...
..MBBBBM..
..BSSSBB..
..BEEBSB..
..BSSSBB..
...BBBB...
..MBBBBM..
..MBmmBM..
...BBBB...
...B..B...
...B..B...
...b..b...`,
            `...MMMM...
..MBBBBM..
..BSSSBB..
..BEEBSB..
..BSSSBB..
...BBBB...
..MBBBBM..
..MBmmBM..
...BBBB...
..B....B..
..b....b..
...b..b...`,
        ]
    },
    fast: {
        colors: {
            '.': null, ' ': null,
            'B': '#553388', 'b': '#331166', // Purple body
            'E': '#ffff00', 'e': '#cccc00',
            'C': '#7744aa', 'c': '#442277', // Cape
            'D': '#221144',
        },
        frames: [
            // 8x10 fast assassin
            `..CCCC..
.CBBBBC.
.BEEEBB.
.BBBBBB.
..BBBB..
.CCBBCC.
.C.BB.C.
..BBBB..
..B..B..
..b..b..`,
            `..CCCC..
.CBBBBC.
.BEEEBB.
.BBBBBB.
..BBBB..
.CCBBCC.
.C.BB.C.
...BB...
..B..B..
.b....b.`,
        ]
    },
    tank: {
        colors: {
            '.': null, ' ': null,
            'A': '#778899', 'a': '#556677', // Heavy armor
            'B': '#667788', 'b': '#445566',
            'E': '#ff3333',
            'G': '#aabbcc', 'g': '#8899aa', // Gold trim
            'S': '#334455', // Shield
        },
        frames: [
            // 14x14 heavy warrior
            `....GGGGGG....
...GAAAAAAG...
..GAABBAAG...
..GA.EE.AG...
..GAABBAAG...
...GAAAAG....
..SAAAAAAA...
.SSAAGAAAA..
.SSAAGAAAS..
..SAAAAAS...
...AAAA.....
...A..A.....
...A..A.....
...a..a.....`,
            `....GGGGGG....
...GAAAAAAG...
..GAABBAAG...
..GA.EE.AG...
..GAABBAAG...
...GAAAAG....
..SAAAAAAA...
.SSAAGAAAA..
.SSAAGAAAS..
..SAAAAAS...
...AAAA.....
..A....A....
..a....a....
...a..a.....`,
        ]
    },
    elite: {
        colors: {
            '.': null, ' ': null,
            'G': '#ffdd00', 'g': '#ccaa00', // Gold
            'A': '#cc3333', 'a': '#991111', // Red armor
            'B': '#882222', 'b': '#661111',
            'E': '#ffffff',
            'C': '#ff4444', 'c': '#cc2222', // Cape
            'M': PAL.metal,
        },
        frames: [
            // 14x16 elite general
            `....GgGgG.....
.....GGG......
...GAAAAAG....
..GAABBAAG...
..GA.EE.AG...
..GAABBAAG...
...GAAAAAG...
.CCAAAAAAC..
.CCAAGAAAC..
.CCAAGAAAC..
..CAAAAAAC..
...AABBAA...
...A....A...
...A....A...
...a....a...
...MM..MM...`,
            `....GgGgG.....
.....GGG......
...GAAAAAG....
..GAABBAAG...
..GA.EE.AG...
..GAABBAAG...
...GAAAAAG...
.CCAAAAAA.C.
.CCAAGAAA.C.
.CCAAGAAA.C.
..CAAAAAA.C.
...AABBAA...
..A......A..
..a......a..
...a....a...
...MM..MM...`,
        ]
    },
    boss: {
        colors: {
            '.': null, ' ': null,
            'R': '#cc2222', 'r': '#991111', // Red body
            'D': '#ff4444', 'd': '#cc3333', // Demon glow
            'B': '#661111', 'b': '#440000',
            'E': '#ffff00', 'e': '#ffcc00', // Yellow eyes
            'H': '#ff6666', 'h': '#cc4444', // Horns
            'G': '#ffdd00', // Gold
            'W': '#ffffff',
        },
        frames: [
            // 22x24 demon lord boss
            `......H....H......
.....HH....HH.....
....HHH....HHH....
...HRRRRRRRRRRH...
..HRRRRRRRRRRRH..
..RRRREEEERRRR..
..RRRRWWWWRRRR..
..RRRREEEERRRR..
...RRRRRRRRRR...
....RRRRRRRR....
..DDRRRRRRRRDD..
.DDDRRGGRRRDDDD.
.DDDRRGGRRRDDD..
.DDDRRRRRRRDDDD.
..DDRRRRRRRDD...
...DRRRRRRD.....
....RRRRR......
....RR.RR......
...RR...RR.....
..RR.....RR....
..rr.....rr....
..BB.....BB....
..BB.....BB....
..bb.....bb....`,
            `......H....H......
.....HH....HH.....
....HHH....HHH....
...HRRRRRRRRRRH...
..HRRRRRRRRRRRH..
..RRRREEEERRRR..
..RRRRWWWWRRRR..
..RRRREEEERRRR..
...RRRRRRRRRR...
....RRRRRRRR....
.DDDRRRRRRRRDDDD
.DDDRRGGRRRDDD..
.DDDRRGGRRRDDDD.
..DDRRRRRRRDD...
..DDRRRRRRRDDD..
...DRRRRRRD.....
....RRRRRR.....
...RR...RR.....
...RR...RR.....
..RR.....RR....
..rr.....rr....
..BB.....BB....
..BB.....BB....
..bb.....bb....`,
        ]
    },
    // --- MINI-BOSS: Commanding General (larger than elite, with cape and crown) ---
    miniboss: {
        colors: {
            '.': null, ' ': null,
            'C': '#ffd700', 'c': '#ccaa00', // Crown/gold
            'R': '#cc2222', 'r': '#991111', // Red cape
            'A': '#883333', 'a': '#662222', // Armor
            'B': '#553333', 'b': '#441111',
            'E': '#ffffff', 'e': '#ffcc00', // Eyes
            'G': '#ffaa00', 'g': '#cc7700', // Gold trim
            'M': PAL.metal, 'm': PAL.metalDark,
            'W': '#aaaacc', // Weapon
        },
        frames: [
            // 16x20 general with cape and crown
            `....CcCcC.......
.....CCC........
...GAAAAAG......
..GAABBAAG......
..GA.EE.AG......
..GAABBAAG......
...GAAAAAG......
.RRAAAAAAA......
.RRAAGAAAA.W....
.RRAAGAAAA.W....
..RAAAAAAA.W....
..RAAABBAA......
...AABBAA.......
...A....A.......
...A....A.......
...a....a.......
..MM....MM......
..MM....MM......
..mm....mm......
..mm....mm......`,
            `....CcCcC.......
.....CCC........
...GAAAAAG......
..GAABBAAG......
..GA.EE.AG......
..GAABBAAG......
...GAAAAAG......
.RRAAAAAA.......
.RRAAGAAAA..W...
.RRAAGAAAA..W...
..RAAAAAAA..W...
..RAAABBAA......
...AABBAA.......
..A......A......
..a......a......
...a....a.......
..MM....MM......
..MM....MM......
..mm....mm......
..mm....mm......`,
        ]
    },
    // --- FINAL BOSS: Massive Demon Tyrant (largest sprite, horns + fire aura)
    finalboss: {
        colors: {
            '.': null, ' ': null,
            'R': '#cc0000', 'r': '#880000', // Red body
            'D': '#ff2200', 'd': '#cc1100', // Demon glow
            'B': '#440000', 'b': '#220000',
            'H': '#ff4444', 'h': '#cc3333', // Horns
            'E': '#ffff00', 'e': '#ffcc00', // Eyes
            'G': '#ffd700', 'g': '#ccaa00', // Gold crown
            'W': '#ffffff',
            'F': '#ff6600', 'f': '#ff4400', // Fire
            'C': '#ffaa00',                  // Cape
        },
        frames: [
            // 22x26 massive demon tyrant
            `.....H......H.....
....HH......HH....
...HHH......HHH...
..HHHH......HHHH..
.HH..GGGGGGGG..HH.
....GRRRRRRRRRG....
...GRRRRRRRRRRG....
...RRRREEEERRRRR...
...RRRRWWWWRRRRR...
...RRRREEEERRRRR...
....RRRRRRRRRR.....
.CCCRRRRRRRRRRCCC..
.CCCRRRRRRRRRRCCCC.
.CCCRRRGGGRRRRCCC..
.CCCRRRGGGRRRRCCCC.
..CCRRRRRRRRRCC....
...CRRRRRRRRC......
....RRRRRRRR.......
....RRR.RRRR.......
...RRR...RRR.......
..RRR.....RRR......
..rrr.....rrr......
..BBB.....BBB......
..BBB.....BBB......
..bbb.....bbb......
..bbb.....bbb......`,
            `.....H......H.....
....HH......HH....
...HHH......HHH...
..HHHH......HHHH..
.HH..GGGGGGGG..HH.
....GRRRRRRRRRG....
...GRRRRRRRRRRG....
...RRRREEEERRRRR...
...RRRRWWWWRRRRR...
...RRRREEEERRRRR...
....RRRRRRRRRR.....
.CCCRRRRRRRRRR.CCC.
.CCCRRRRRRRRRR.CCC.
.CCCRRRGGGRRRRCCCC.
..CCRRRGGGRRRRCCCC.
..CCRRRRRRRRRCC....
...CRRRRRRRRC......
....RRRRRRRRR......
...RRR...RRRR......
...RRR...RRR.......
..RRR.....RRR......
..rrr.....rrr......
..BBB.....BBB......
..BBB.....BBB......
..bbb.....bbb......
..bbb.....bbb......`,
        ]
    },
    // --- ARCHER: Hooded ranger with bow ---
    archer: {
        colors: {
            '.': null, ' ': null,
            'B': '#336633', 'b': '#224422', // Green hood/body
            'E': '#ffaa00', 'e': '#cc8800', // Eyes
            'S': PAL.skin, 's': PAL.skinShadow,
            'W': '#8B6914', 'w': '#6B4914', // Bow wood
            'A': '#cc8833',                  // Arrow
            'C': '#445533',                  // Cape
        },
        frames: [
            // 12x12 hooded archer
            `...BBBB.....
..BBBBBB....
..BSSSBB....
..BEEBB.....
..BSSBB.....
...BBB......
..CBBBC.W...
..CBBBCwW...
..C.BB.CW.A.
...BBBB.W...
...B..B.....
...b..b.....`,
            `...BBBB.....
..BBBBBB....
..BSSSBB....
..BEEBB.....
..BSSBB.....
...BBB......
..CBBBC..W..
..CBBBCW.W..
..C.BB.WW.A.
...BBBB.....
..B....B....
..b....b....`,
        ]
    },
    // --- SHAMAN: Robed healer with glowing staff ---
    shaman: {
        colors: {
            '.': null, ' ': null,
            'B': '#553388', 'b': '#331166', // Purple robes
            'E': '#44ff44', 'e': '#22cc22', // Green glowing eyes
            'G': '#44ff44', 'g': '#22cc22', // Staff glow
            'W': '#776655', 'w': '#554433', // Staff
            'R': '#664499', 'r': '#442277', // Robe trim
            'S': PAL.skin, 's': PAL.skinShadow,
        },
        frames: [
            // 12x14 shaman
            `.......G....
......gWg...
...BBBBB.W..
..BBBBBB.W..
..BSSSBB.W..
..BEEBB..W..
..BSSBB..W..
...BBB...W..
.RRBBBRRR...
.RRBBBRRR...
..RBBBRR....
...BBBB.....
...B..B.....
...b..b.....`,
            `.......G....
......gWg...
...BBBBB.W..
..BBBBBB.W..
..BSSSBB.W..
..BEEBB..W..
..BSSBB..W..
...BBB...W..
.RRBBBRRR...
.RRBBBRRR...
..RBBBRR....
...BBBB.....
..B....B....
..b....b....`,
        ]
    },
    // --- BOMBER: Small explosive imp ---
    bomber: {
        colors: {
            '.': null, ' ': null,
            'R': '#cc3300', 'r': '#991100', // Red body
            'E': '#ffff00', 'e': '#ffcc00', // Yellow eyes
            'B': '#ff6600', 'b': '#cc4400', // Bomb
            'F': '#ffaa00', 'f': '#ff8800', // Fuse/fire
            'D': '#442200',                  // Dark
        },
        frames: [
            // 8x10 small bomber imp
            `..fBBf..
..BBBB..
.RREERRR
.RRRRRR.
..RRRR..
..RRRR..
..rRRr..
..r..r..
..D..D..
..D..D..`,
            `..fBBf..
..BBBB..
.RREERRR
.RRRRRR.
..RRRR..
..RRRR..
..rRRr..
.r....r.
.D....D.
..D..D..`,
        ]
    },
    // --- SHIELDWALL: Heavy knight with tower shield ---
    shieldwall: {
        colors: {
            '.': null, ' ': null,
            'A': '#556677', 'a': '#445566', // Heavy armor
            'B': '#667788', 'b': '#445566',
            'E': '#ff3333',
            'G': '#889999', 'g': '#667777', // Shield face
            'S': '#778899', 's': '#556677', // Shield
            'M': PAL.metal, 'm': PAL.metalDark,
            'R': '#aabbcc', // Rivets
        },
        frames: [
            // 14x16 heavy shieldwall
            `....MMMMMM....
...MAAAAAAM...
..MAABBAAAM...
..MA.EE.AAM...
..MAABBAAM....
...MAAAAAAM...
SSSAAAAAAA....
SGGSAAGAAAA...
SGGSAAGAAAS...
SRRSAAAAAAS...
SSSAAAAA......
....AABBAA....
....A....A....
....A....A....
....a....a....
...MM....MM...`,
            `....MMMMMM....
...MAAAAAAM...
..MAABBAAAM...
..MA.EE.AAM...
..MAABBAAM....
...MAAAAAAM...
SSSAAAAAAA....
SGGSAAGAAAA...
SGGSAAGAAAS...
SRRSAAAAAAS...
SSSAAAAA......
....AABBAA....
...A......A...
...a......a...
....a....a....
...MM....MM...`,
        ]
    }
};

// --- PICKUP SPRITES ---
const PICKUP_SPRITES = {
    xp: {
        colors: { '.': null, 'G': '#44ff44', 'g': '#22cc22', 'L': '#88ff88' },
        frame: `..L..
.GGG.
GGGGG
.GGG.
..g..`
    },
    gold: {
        colors: { '.': null, 'G': '#ffdd00', 'g': '#ccaa00', 'L': '#ffee66' },
        frame: `.LLL.
GGGGG
GGLGG
GGGGG
.ggg.`
    },
    hp: {
        colors: { '.': null, 'R': '#ff3333', 'r': '#cc1111', 'W': '#ffffff' },
        frame: `..R..
.RRR.
RRWRR
.RRR.
..r..`
    }
};

// --- SPRITE RENDERING ---
function parseSprite(str, colorMap) {
    const lines = str.trim().split('\n');
    const frames = [];
    for (const line of lines) {
        const row = [];
        for (const ch of line) {
            row.push(colorMap[ch] || null);
        }
        frames.push(row);
    }
    return frames;
}

// Draw a sprite from string definition
function drawSprite(x, y, spriteStr, colorMap, flipX, tint) {
    const lines = spriteStr.trim().split('\n');
    const h = lines.length;
    const w = lines.reduce((max, l) => Math.max(max, l.length), 0);
    const ox = Math.round(x - w / 2);
    const oy = Math.round(y - h);

    for (let row = 0; row < h; row++) {
        const line = lines[row];
        for (let col = 0; col < line.length; col++) {
            const ch = line[col];
            const color = colorMap[ch];
            if (!color) continue;

            const px = flipX ? ox + (w - 1 - col) : ox + col;
            const py = oy + row;

            if (tint) {
                ctx.fillStyle = tint;
            } else {
                ctx.fillStyle = color;
            }
            ctx.fillRect(px, py, 1, 1);
        }
    }
}

// --- HERO-SPECIFIC SPRITES (unique silhouettes per class) ---
const HERO_SPRITES = {
    berserker: {
        // Lu Bu — Horned helmet, massive halberd held upright, heavy red armor
        colors: {
            '.': null, ' ': null,
            'H': '#660000', 'h': '#440000',  // Horns (dark red)
            'K': PAL.hair, 'k': PAL.hairDark,
            'S': PAL.skin, 's': PAL.skinShadow, 'L': PAL.skinLight,
            'E': PAL.eyeW, 'P': PAL.eyeP,
            'A': '#cc2222', 'a': '#ff6644',  // Red armor
            'M': PAL.metal, 'm': PAL.metalDark,
            'W': '#ff4400', 'w': '#cc3300',  // Weapon (fire halberd)
            'B': PAL.leather, 'b': PAL.leatherDark,
        },
        idle: [
            `......W.......
.....WW.......
....HH.HH.....
...HKKKKH.....
...KSSHK......
...SEEPS......
...SSSSS......
..AAAAAAA.....
..AAmMAAA.....
..AA.AA.A.....
..AAAAAAA.....
...BBBB.......
...B..B.......
...B..B.......
...b..b.......
...MM.MM......`,
            `......W.......
.....WW.......
....HH.HH.....
...HKKKKH.....
...KSSHK......
...SEEPS......
...SSSSS......
..AAAAAAA.....
..AAmMAAA.....
..AA.AA.A.....
..AAAAAAA.....
...BBBB.......
...B..B.......
...B..B.......
...b..b.......
..MM..MM......`
        ],
        walk: [
            `......W.......
.....WW.......
....HH.HH.....
...HKKKKH.....
...KSSHK......
...SEEPS......
...SSSSS......
..AAAAAAA.....
..AAmMAAA.....
..AA.AA.A.....
..AAAAAAA.....
...BBBB.......
..B....B......
..b....b......
..MM..MM......
.MM....MM.....`,
            `......W.......
.....WW.......
....HH.HH.....
...HKKKKH.....
...KSSHK......
...SEEPS......
...SSSSS......
..AAAAAAA.....
..AAmMAAA.....
..AA.AA.A.....
..AAAAAAA.....
...BBBB.......
....BB........
....bb........
...MMMM.......
...MMMM.......`
        ]
    },
    strategist: {
        // Zhuge Liang — Tall scholar hat, flowing green robes, feather fan
        colors: {
            '.': null, ' ': null,
            'T': '#338833', 't': '#226622',  // Tall hat
            'K': PAL.hair, 'k': PAL.hairDark,
            'S': PAL.skin, 's': PAL.skinShadow, 'L': PAL.skinLight,
            'E': PAL.eyeW, 'P': PAL.eyeP,
            'A': '#226622', 'a': '#55cc55',  // Green robes
            'R': '#338844', 'r': '#225533',  // Robe trim
            'F': '#44ff44', 'f': '#88ff88',  // Fan
            'M': PAL.metal, 'm': PAL.metalDark,
        },
        idle: [
            `....TTT.......
...TTTTT......
...tTTTt......
...KSSKK......
...SEEPK......
....SSS.......
..RAAAAAR.....
..RAAARAAR....
..RA.AA.AR...f
..RAAAAAAR..ff
...RRRRRR..fFf
....AAAA...fFf
....A..A....ff
....A..A......
....m..m......
....m..m......`,
            `....TTT.......
...TTTTT......
...tTTTt......
...KSSKK......
...SEEPK......
....SSS.......
..RAAAAAR.....
..RAAARAAR....
..RA.AA.AR..f.
..RAAAAAAR.ff.
...RRRRRR.fFf.
....AAAA..fFf.
....A..A...ff.
....A..A......
...mm..mm.....
...mm..mm.....`
        ],
        walk: [
            `....TTT.......
...TTTTT......
...tTTTt......
...KSSKK......
...SEEPK......
....SSS.......
..RAAAAAR.....
..RAAARAAR....
..RA.AA.AR...f
..RAAAAAAR..ff
...RRRRRR..fFf
....AAAA...fFf
...A....A...ff
...a....a.....
..mm....mm....
..mm....mm....`,
            `....TTT.......
...TTTTT......
...tTTTt......
...KSSKK......
...SEEPK......
....SSS.......
..RAAAAAR.....
..RAAARAAR....
..RA.AA.AR...f
..RAAAAAAR..ff
...RRRRRR..fFf
....AAAA...fFf
.....AA.......
.....aa.......
....mmmm......
....mmmm......`
        ]
    },
    assassin: {
        // Zhou Yu — Sleek silver armor, cape, twin swords crossed
        colors: {
            '.': null, ' ': null,
            'K': '#333355', 'k': '#222244',  // Dark hair
            'S': PAL.skin, 's': PAL.skinShadow, 'L': PAL.skinLight,
            'E': PAL.eyeW, 'P': PAL.eyeP,
            'A': '#7777aa', 'a': '#ccccff',  // Silver armor
            'C': '#5566aa', 'c': '#334477',  // Cape
            'W': '#aaaaff', 'w': '#8888cc',  // Twin blades
            'M': PAL.metal, 'm': PAL.metalDark,
        },
        idle: [
            `W...KKKK...W..
.W.KKkKKK.W...
..WKSSHK.W....
...SEEPS......
....SSS.......
..CAAAAAC.....
..CAAMAACw....
..CA.AA.AC.w..
..CAAAAAC..w..
...CCCC.......
...AAAA.......
...A..A.......
...A..A.......
...m..m.......
...m..m.......`,
            `W...KKKK...W..
.W.KKkKKK.W...
..WKSSHK.W....
...SEEPS......
....SSS.......
..CAAAAAC.....
..CAAMAACw....
..CA.AA.AC.w..
..CAAAAAC..w..
...CCCC.......
...AAAA.......
...A..A.......
...A..A.......
..mm..mm......
..mm..mm......`
        ],
        walk: [
            `W...KKKK...W..
.W.KKkKKK.W...
..WKSSHK.W....
...SEEPS......
....SSS.......
..CAAAAAC.....
..CAAMAACw....
..CA.AA.AC.w..
..CAAAAAC..w..
...CCCC.......
...AAAA.......
..A....A......
..a....a......
..mm..mm......
.mm....mm.....`,
            `W...KKKK...W..
.W.KKkKKK.W...
..WKSSHK.W....
...SEEPS......
....SSS.......
..CAAAAAC.....
..CAAMAACw....
..CA.AA.AC.w..
..CAAAAAC..w..
...CCCC.......
...AAAA.......
....AA........
....aa........
...mmmm.......
...mmmm.......`
        ]
    },
    vanguard: {
        // Zhao Yun — Heavy plate armor, shield on arm, long spear
        colors: {
            '.': null, ' ': null,
            'K': '#553311', 'k': '#331100',  // Brown hair
            'S': PAL.skin, 's': PAL.skinShadow, 'L': PAL.skinLight,
            'E': PAL.eyeW, 'P': PAL.eyeP,
            'A': '#886622', 'a': '#ddaa44',  // Gold/brown armor
            'D': '#aa8833', 'd': '#776622',  // Shield
            'W': '#ffcc00', 'w': '#ddaa00',  // Spear (gold)
            'G': '#ffd700', 'g': '#ccaa00',  // Gold trim
            'M': PAL.metal, 'm': PAL.metalDark,
        },
        idle: [
            `........W.....
........W.....
...GKKKG......
..GKSSHKG.....
...SEEPS......
....SSS.......
.DDAAAAAA.....
.DDAGmAAA.....
.DDAA.AAA.....
.DDAAAAAA.....
...GGGG.......
...AAAA.......
...A..A.......
...A..A.......
...m..m.......
...MM.MM......`,
            `........W.....
........W.....
...GKKKG......
..GKSSHKG.....
...SEEPS......
....SSS.......
.DDAAAAAA.....
.DDAGmAAA.....
.DDAA.AAA.....
.DDAAAAAA.....
...GGGG.......
...AAAA.......
...A..A.......
...A..A.......
...m..m.......
..MM..MM......`
        ],
        walk: [
            `........W.....
........W.....
...GKKKG......
..GKSSHKG.....
...SEEPS......
....SSS.......
.DDAAAAAA.....
.DDAGmAAA.....
.DDAA.AAA.....
.DDAAAAAA.....
...GGGG.......
...AAAA.......
..A....A......
..a....a......
..MM..MM......
.MM....MM.....`,
            `........W.....
........W.....
...GKKKG......
..GKSSHKG.....
...SEEPS......
....SSS.......
.DDAAAAAA.....
.DDAGmAAA.....
.DDAA.AAA.....
.DDAAAAAA.....
...GGGG.......
...AAAA.......
....AA........
....aa........
...MMMM.......
...MMMM.......`
        ]
    },
    mystic: {
        // Sima Yi — Hood/cowl, dark blue robes, glowing staff
        colors: {
            '.': null, ' ': null,
            'H': '#111144', 'h': '#0a0a33',  // Hood
            'S': PAL.skin, 's': PAL.skinShadow, 'L': PAL.skinLight,
            'E': PAL.eyeW, 'P': PAL.eyeP,
            'A': '#223388', 'a': '#5588ff',  // Dark blue robes
            'R': '#334499', 'r': '#223366',  // Robe trim
            'G': '#4466ff', 'g': '#6688ff',  // Staff glow
            'W': '#556688', 'w': '#445577',  // Staff
            'M': PAL.metal, 'm': PAL.metalDark,
        },
        idle: [
            `..........G...
.HHHHH....g...
HHHHHHH...W...
HH.SS.HH..W..
...SEEP....W..
....SS.....W..
..RAAAAAR..W..
..RAAmAAR..W..
..RA.AAAR.....
..RAAAAAAR....
...RRRRRR.....
....AAAA......
....A..A......
....A..A......
....m..m......
....m..m......`,
            `..........G...
.HHHHH....g...
HHHHHHH...W...
HH.SS.HH..W..
...SEEP....W..
....SS.....W..
..RAAAAAR..W..
..RAAmAAR..W..
..RA.AAAR.....
..RAAAAAAR....
...RRRRRR.....
....AAAA......
....A..A......
....A..A......
....m..m......
...mm..mm.....`
        ],
        walk: [
            `..........G...
.HHHHH....g...
HHHHHHH...W...
HH.SS.HH..W..
...SEEP....W..
....SS.....W..
..RAAAAAR..W..
..RAAmAAR..W..
..RA.AAAR.....
..RAAAAAAR....
...RRRRRR.....
....AAAA......
...A....A.....
...a....a.....
...mm..mm.....
..mm....mm....`,
            `..........G...
.HHHHH....g...
HHHHHHH...W...
HH.SS.HH..W..
...SEEP....W..
....SS.....W..
..RAAAAAR..W..
..RAAmAAR..W..
..RA.AAAR.....
..RAAAAAAR....
...RRRRRR.....
....AAAA......
.....AA.......
.....aa.......
....mmmm......
....mmmm......`
        ]
    }
};

// Draw player with hero-specific sprite (or fallback generic)
function drawPlayerSprite(x, y, element, frame, flipX, tint) {
    const heroSprite = HERO_SPRITES[P.heroId];

    if (heroSprite) {
        // Use hero-specific sprite
        if (P.damageFlash > 0) tint = '#ffffff';

        const isMoving = Math.abs(P.vx) > 5 || Math.abs(P.vy) > 5;
        let anim, frameIdx;
        if (isMoving) {
            anim = heroSprite.walk;
            frameIdx = Math.floor(G.time * 8) % anim.length;
        } else {
            anim = heroSprite.idle;
            frameIdx = Math.floor(G.time * 2) % anim.length;
        }

        drawSprite(x, y, anim[frameIdx], heroSprite.colors, flipX, tint);
    } else {
        // Fallback to generic element-colored sprite
        const el = ELEMENTS[element];
        const armorMain = el.color;
        const armorDark = el.light;
        const colors = { ...PLAYER_COLORS, 'A': armorMain, 'a': armorDark };

        if (P.damageFlash > 0) tint = '#ffffff';

        const isMoving = Math.abs(P.vx) > 5 || Math.abs(P.vy) > 5;
        let anim, frameIdx;
        if (isMoving) {
            anim = PLAYER_FRAMES.walk;
            frameIdx = Math.floor(G.time * 8) % anim.length;
        } else {
            anim = PLAYER_FRAMES.idle;
            frameIdx = Math.floor(G.time * 2) % anim.length;
        }
        drawSprite(x, y, anim[frameIdx], colors, flipX, tint);
    }
}

// Draw enemy sprite
function drawEnemySprite(ex, ey, enemy, tint) {
    const def = ENEMY_SPRITES[enemy.type];
    if (!def) {
        // Fallback for unknown types - draw colored rect
        ctx.fillStyle = tint || enemy.color;
        ctx.fillRect(ex - enemy.r, ey - enemy.r, enemy.r * 2, enemy.r * 2);
        return;
    }

    const frameIdx = Math.floor(G.time * 4) % def.frames.length;
    const flipX = enemy.vx < 0;
    drawSprite(ex, ey, def.frames[frameIdx], def.colors, flipX, tint);
}

// Draw pickup sprite
function drawPickupSprite(x, y, type) {
    const def = PICKUP_SPRITES[type];
    if (!def) return;

    const bounce = Math.sin(G.time * 5 + x * 0.1) * 2;
    drawSprite(x, y + bounce, def.frame, def.colors, false, null);
}

// --- ANIMATION HELPERS ---
function getPlayerAnimFrame() {
    const isMoving = Math.abs(P.vx) > 5 || Math.abs(P.vy) > 5;
    if (isMoving) {
        return { anim: 'walk', frame: Math.floor(G.time * 8) % PLAYER_FRAMES.walk.length };
    }
    return { anim: 'idle', frame: Math.floor(G.time * 2) % PLAYER_FRAMES.idle.length };
}
